### ISSUE TITLE
please update to 3.16

### ISSUE THREAD

**Issue by ingerling** [xmikos/fdroiddata#23]
Could you please update to version 3.16?
3.15.2 is deprecated. 
Or is this fdroid repo abandoned as https://github.com/LibreSignal/LibreSignal ?
In that case, is it possible to built the app easily by myself (never did that before)?

Thank you for your efforts!

**Comment by ClubWDW** [comment]
Please, oh, please....and thank you!!!

**Comment by Heimdal300** [comment]
An Update is necessary!  I use Copperhead OS and LibreSignal is the only way to contact Signal-Users via my phone. If the LibreSignal repo isn't supported anymore and there is no way to build it, i have to switch back to Google or Cyanogenmod, witch are both less secure or have to communicate with Signal-Users on an unsecure way. So please continue supporting LibreSignal an thanks for your work!

**Comment by mimi89999** [comment]
If you are using the 'standard' version, you can download the app using a website that lets you download apk from the Play Store. If you use the WebSocket version because you don't have gapps, you need to wait for me to update the LibreSignal Github repo, which I will try to do today and then ask @xmikos to update the Eutopia experimental F-Droid repo.

**Comment by mimi89999** [comment]
And please, please try to move to another app like Conversations. It is an XMPP client, that is quite user friendly and has more features than LibreSignal.

**Comment by ingerling** [comment]
I use the "standard" one with microg, but from the eutopia repo.
I'd love to move to a different messenger, but I can't.

**Comment by mimi89999** [comment]
Why you can't? If you and your contacts care about security and privacy, you really should.

**Comment by xmikos** [comment]
I will definitely update (and keep updated in the future) builds from official Signal sources in my main repository. It will be updated today (after I audit latest code changes).

But future of WebSocket fork (from experimental repository) is uncertain.

@mimi89999 Do you want to still maintain LibreSignal (WebSocket fork) at least until there is good alternative (both Android and iOS, with default Axolotl-based encryption and simple setup - so probably future versions of ChatSecure and/or Zom)? If yes, I will audit code diffs and will keep experimental repo updated...

**Comment by Heimdal300** [comment]
I will try to use a different app in the future, but i need time to contact and convince my friends that Signal isn't the best option for E2E-messaging anymore. Some time ago i testet ChatSecure and it drained the battery of my phone even faster than LibreSignal with websocket: If such problems are fixed in Conversations or future ChatSecure Version there is no need for Singal/LibreSignal anymore. Actually I see no other way than using LibreSignal or replace CopperheadOS with an System that supports GCM (which is really a bad option). So please continue supporting websocket-Version of LibreSignal until there is a fully equivalent alternative! Do you see any chance that ChatSecure oder Conversations are compatible with Signal in the future?

**Comment by xmikos** [comment]
@Heimdal300 I am working on an automated CopperheadOS image modification utility, which will allow you to make changes to CopperheadOS factory images / updates and resign them with your own key. I want it to allow people to have locked bootloader but still be able to do offline updates (signed with their own key). It should be easy to add GApps, microG and root access (with opensource seSuperUser app) with it.

It is not finished, I didn't have time to work on it recently. But it is on my TODO list and I want to finish it in near future...

**Comment by Heimdal300** [comment]
@xmikos Your CopperheadOS image modification utility sounds great! This would be a (temporary) solution for the LibreSignal/Signal-issue and some other "problems" on CopperheadOS. For your work on the copperhead-project and the support for LibreSignal-websocket I would be pleased to give a little donation to you or a project of your choice. @mimi89999 This goes for you as well! I think the support of LibreSignal-websocket until there is a other good solution (like Briar project, ChatSecure or Conversion with Axolotl and iOS/Android-Support) would be the best way for user like me.

**Comment by idumych** [comment]
Thanks for making this updated build available! I'm kind of wondering what the point was of that message in the last build that said it was going to expire in a few days. I went and looked at the website for LibreSignal, and it says the project is cancelled. Kind of weird to see a new build coming out of something that was just cancelled! I had already fled to Silent.im, and now I'm feeling kind of silly.

**Comment by ingerling** [comment]
Thank you!

**Comment by xmikos** [comment]
@idumych That message about expiration is standard in Signal (not only LibreSignal) if new version is available and older version hasn't been updated for some time.

LibreSignal (WebSocket-fork, in my _experimental_ repo) is really pretty much dead, see my explanation here: https://github.com/xmikos/fdroiddata/issues/24#issuecomment-226911928. But I will still provide independent builds from official Signal sources in my _main_ repo on https://fdroid.eutopia.cz.
