### ISSUE TITLE
Publish LibreSignal in official F-Droid repository

### ISSUE THREAD

**Issue by PanderMusubi** [xmikos/fdroiddata#29]
Please, publish LibreSignal in F-Droid repository. For some of my contacts it has been a huge step to switch to F-Droid. Having them add repositories without fingerprint will only add confusion and result in less trust. Publishing LibreSignal in F-Droid will increase the use base quickly and eventually lessen the burden to maintain a separate repo.

PS  I know F-Droid is designed to add repo's manually, but if all apps have their own repo, the entire idea of an app store is gone.

**Comment by xmikos** [comment]
This will sadly not happen. Signal already has been in official F-Droid repo in the past (for a brief time), but it has been removed because Moxie Marlinspike (author of Signal) didn't like it and demanded it to be removed.

**Comment by PanderMusubi** [comment]
Just heard about this:

    commit 1669731329bcc32c84e33035a67a2fc22444c24b
    Author: Moxie Marlinspike
    Date:   Mon Feb 20 12:00:03 2017 -0800
    Support for using Signal without Play Services
    This is now possible with beta calling, so non-GCM users are a
    part of beta calling by default.

**Comment by anarcat** [comment]
Update: I have moved this comment to the [public OWS community forum](https://whispersystems.discoursehosting.net/t/how-to-get-signal-apks-outside-of-the-google-play-store/808) since it seems like the right forum for this discussion.

**Comment by Be-ing** [comment]
Thanks for the detailed summary @anarcat .

**Comment by herbsmn** [comment]
@xmikos can you open this issue back up since @anarcat wrote that report? or should they publish the report elsewhere?

**Comment by xmikos** [comment]
@herbsmn I have reopened it, but I am not completely sure if this is proper place to discuss it.

**Comment by Be-ing** [comment]
Moxie just commented on [the commit](https://github.com/WhisperSystems/Signal-Android/commit/1669731329bcc32c84e33035a67a2fc22444c24b) outlining what he wants before releasing official APKs outside of the Google Play Store.

**Comment by anarcat** [comment]
alright - i updated my comment above with the relevant changes. i also opened a [new thread](https://whispersystems.discoursehosting.net/t/how-to-get-signal-apks-outside-of-the-google-play-store/808) in the OWS forum about this. i would have preferred moving my lengthy comment there and close the discussion here, but i wasn't able to post the full thing because I was limited to 10 links as a new user, probably a sort of anti-spam measure...

update: the restrictions were lifted, and i have moved the post there. I guess we can close this again now?
